[project]
name = "vega"
version = "0.0.0"
description = "VEGA python project"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
