version: "3.3"

services:
  db:
    image: elestio/mysql:8.0
    restart: always
    stdin_open: true
    ports:
      - "3904:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ITOP_DB_NAME}
      MYSQL_USER: ${ITOP_DB_USER}
      MYSQL_PASSWORD: ${ITOP_DB_PASS}
    volumes:
      - ./storage/mysql:/var/lib/mysql

  itop:
    image: elestio/itop:latest
    restart: always
    stdin_open: true
    environment:
      ITOP_DB_HOST: ${ITOP_DB_HOST}
      ITOP_DB_NAME: ${ITOP_DB_NAME}
      ITOP_DB_USER: ${ITOP_DB_USER}
      ITOP_DB_PASS: ${ITOP_DB_PASS}
      PHP_ENABLE_UPLOADS: ${PHP_ENABLE_UPLOADS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_MAX_FILE_UPLOADS: ${PHP_MAX_FILE_UPLOADS}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME}
      PHP_LOG_ERRORS: ${PHP_LOG_ERRORS}
      PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING}
    ports:
      - "9904:80"
    volumes:
      - ./storage/itop/conf:/var/www/itop/conf
      - ./storage/itop/data:/var/www/itop/data
      - ./storage/itop/log:/var/www/itop/log
      - ./storage/itop/env-production:/var/www/itop/env-production
      - ./storage/itop/env-production-build:/var/www/itop/env-production-build
      - ./storage/extensions:/var/www/itop/extensions
    depends_on:
      - db

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8111:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
    depends_on:
      - db
